  name: Android Build
  on: 

   push:
    branches: [main]
  jobs:

    install-and-test:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - name: install node modules
            run: yarn install

    android-build:
          needs: install-and-test
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v3
            - name: Android buld Release
              run: cd android && ./gradlew assembleRelease
            - name: upload Artifact
              uses: actions/checkout@v1
              with: 
                name: app-release.apk
                path: android/app/build/output/apk/release